title: Jekyll Website
description: >-
  Write an awesome description for your new site here. You can edit this line in
  _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ""
url: ""

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post

plugins:
  - jekyll-seo-tag

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - tailwind.config.js
  - assets/scss/
